### ISSUE TITLE
Rng is not implemented

### ISSUE THREAD

**Issue by SymmetricChaos** [rust-random/rngs#39]
Anything from rand with a trait bound that requires Rng doesn't work. It looks like the Rng trait became a part of rand and this was never updated?

**Comment by dhardy** [comment]
Do you have multiple `rand` or `rand_core` versions in your dependencies? Check with [cargo-tree](https://crates.io/crates/cargo-tree) (or your `Cargo.toml`). Or try running `cargo update`.

**Comment by dhardy** [comment]
I can't follow what the actual issue is given your description. Yes, `Rng` is part of the `rand` crate (and has been since v0.3 at least). It sound like you may have incompatible `rand` / `rand_core` versions, which is only possible given *multiple* `rand_core` versions in your dependency tree (hence my previous comment).

I'm closing this issue since its too vague to be actionable, but feel free to reply with more details anyway if this isn't enough help to solve your problem.
